jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
#    metadata:
#        #auto_detection: true
#        directories:
#            KnpPaginatorBundle:
#                namespace_prefix: Knp\Bundle\PaginatorBundle
#                path: /config/serializer/KnpPaginatorBundle
#            KnpPager:
#                namespace_prefix: Knp\Component\Pager
#                path: kernel.project_dir/config/serializer/KnpPager